<a href="https://colab.research.google.com/github/martinpius/PYTORCH/blob/main/Basic_tensor_operations_in_Pytorch_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#In this notebook we are going to discuss more operations involving tensors in pytorch:

In [2]:
#Imprting and checking the version of the library:

In [3]:
import torch
print(f"You are using pytorch version: {torch.__version__}")

You are using pytorch version: 1.8.1+cu101


In [5]:
#Set up the gpu device:(Not necessarily important):
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

In [13]:
#Defining and indexing high dimensional tensors:

In [14]:
batch_size, features_dimension = 64, 10

In [15]:
data = torch.rand(batch_size,features_dimension)

In [16]:
data.shape

torch.Size([64, 10])

In [17]:
data[0,1]#print out first features of the first sample

tensor(0.4306)

In [18]:
data[0:,1]#print out first feature for 64 samples (64, 1)

tensor([0.4306, 0.3847, 0.3577, 0.2745, 0.6679, 0.7124, 0.5579, 0.0248, 0.1369,
        0.3077, 0.7070, 0.8965, 0.0294, 0.1462, 0.4632, 0.6674, 0.9653, 0.4809,
        0.6203, 0.8605, 0.9091, 0.2375, 0.8325, 0.4182, 0.1368, 0.9671, 0.5832,
        0.0295, 0.6557, 0.8592, 0.9350, 0.5335, 0.3905, 0.1478, 0.5085, 0.4906,
        0.8198, 0.9692, 0.7693, 0.7150, 0.5877, 0.0947, 0.6173, 0.6315, 0.8110,
        0.8769, 0.4432, 0.9287, 0.3530, 0.3850, 0.0856, 0.1794, 0.2968, 0.8524,
        0.0178, 0.1185, 0.7261, 0.0573, 0.7205, 0.3090, 0.2183, 0.4250, 0.3279,
        0.4983])

In [19]:
data[0,1:] #print out all features of sample 1 (1, 10)

tensor([0.4306, 0.3195, 0.8911, 0.6757, 0.0826, 0.2655, 0.7347, 0.2713, 0.0321])

In [21]:
#We can also iterate over the data to print out any part of it:
for t in data[0:3,3:6]:#for the first 3 samples we print featres from third to fith (3,4,5)==shape(3,3)
  print(t)


tensor([0.8911, 0.6757, 0.0826])
tensor([0.5503, 0.1960, 0.2728])
tensor([0.0212, 0.6930, 0.1860])


In [22]:
#We can also do some oprations such as sum, multi, div, abs, argmax,argmin, ect:
print(torch.argmax(data, dim = 1)) #Maximum across first dimension(features) for every sample

tensor([3, 0, 2, 7, 7, 3, 7, 4, 5, 9, 7, 0, 4, 3, 9, 9, 1, 0, 3, 1, 4, 6, 9, 2,
        3, 1, 7, 9, 8, 4, 1, 6, 3, 3, 3, 4, 1, 1, 0, 8, 3, 7, 2, 7, 1, 1, 4, 1,
        0, 3, 0, 9, 8, 5, 6, 0, 8, 2, 5, 0, 5, 8, 0, 5])


In [23]:
print(torch.argmin(data, dim = 1))#same as above but minimum

tensor([9, 8, 3, 1, 3, 0, 4, 1, 0, 6, 6, 5, 1, 1, 0, 4, 2, 8, 9, 0, 9, 2, 0, 7,
        6, 6, 0, 1, 6, 8, 9, 2, 5, 1, 8, 0, 9, 9, 6, 7, 6, 8, 4, 8, 2, 7, 0, 9,
        6, 5, 9, 1, 1, 0, 1, 9, 4, 7, 0, 8, 6, 2, 3, 8])


In [24]:
print(torch.sum(data, dim = 1)) #For every sample it sum accross features

tensor([4.2683, 3.8662, 3.9191, 5.4495, 4.1818, 4.5903, 6.5624, 3.9692, 4.3327,
        5.9408, 5.6117, 6.2155, 5.7945, 5.0035, 4.7998, 4.1431, 5.2330, 5.1600,
        5.4755, 6.1760, 5.2397, 4.9707, 5.0271, 5.5111, 4.0100, 4.1149, 5.0250,
        4.3043, 5.3490, 5.6308, 4.5864, 4.4252, 6.2077, 4.2058, 5.2380, 3.5842,
        3.8370, 5.1539, 5.7442, 4.8946, 5.0333, 4.1032, 4.8975, 4.1743, 4.0056,
        3.5056, 4.4511, 6.2728, 5.4105, 4.6999, 5.1096, 5.2018, 6.7528, 5.7043,
        3.0581, 3.1656, 4.9240, 5.7527, 6.3589, 4.9019, 4.1039, 4.2991, 5.2222,
        3.9279])


In [31]:
print(torch.mm(data, torch.rand(10,10)).shape) #element-wise multiplication

torch.Size([64, 10])


In [33]:
print(torch.exp(data).shape) #get the taylor expansion type of math

torch.Size([64, 10])


In [34]:
#We can also filter our data using some indices:

In [35]:
x = torch.arange(0,10)
indices = [0,5,9]
print(f"x = {x}, filtered_x = {x[indices]}")

x = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), filtered_x = tensor([0, 5, 9])


In [36]:
#We can also select specific row and columns from a high dimension tensor:

In [39]:
rows = torch.tensor([10,20,30])
cols = torch.tensor([0,5,8])
print(data[rows, cols]) # from our previousily defined data we pick columns 0,5, and 8 for samples 10,20, and 30

tensor([0.7644, 0.7739, 0.2881])


In [51]:
#More on indexing a tensor:(can applied to create masks)
x = torch.rand(64,10)

In [54]:
print(data[(x >3)|(x<6)].shape)

torch.Size([640])


In [63]:
#Indexing with some conditions:
x = torch.arange(10)
print(x[x.where(x%2==0, x-2)]) 

tensor([0, 9, 2, 1, 4, 3, 6, 5, 8, 7])


In [66]:
try:
  print(x[x.remainder(2)==0])
except RuntimeError as e:
  print(f"not divisible by zero")

tensor([0, 2, 4, 6, 8])


In [69]:
print(x.where(x>10,x),x*2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [72]:
 print(torch.where(x%2 == 0, x, x*2))

tensor([ 0,  2,  2,  6,  4, 10,  6, 14,  8, 18])


In [71]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [74]:
print(torch.tensor([0,1,2,2,3,4,5,5,5,6,9]).unique())

tensor([0, 1, 2, 3, 4, 5, 6, 9])


In [75]:
tensor = torch.rand(10,10,10,3)

In [76]:
print(tensor.ndimension())#returns the number of dimension for the tensor.

4


In [81]:
print(data.numel()) #return total number of elements in a dataset/tensor/of any dimension

640


In [82]:
#Reshaping the tensors:

In [84]:
A = torch.rand(3,5)
print(f"A3x5 = {A}\nA_5x3 = {A.reshape(5,3)}")

A3x5 = tensor([[0.4457, 0.5364, 0.0775, 0.2252, 0.5754],
        [0.4507, 0.7307, 0.2432, 0.9046, 0.7587],
        [0.2009, 0.8690, 0.1590, 0.4105, 0.0594]])
A_5x3 = tensor([[0.4457, 0.5364, 0.0775],
        [0.2252, 0.5754, 0.4507],
        [0.7307, 0.2432, 0.9046],
        [0.7587, 0.2009, 0.8690],
        [0.1590, 0.4105, 0.0594]])


In [85]:
t = torch.arange(9)
print(t.view(3,3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [86]:
print(t.reshape(3,3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [87]:
print(f"t_trn: {t.t().reshape(3,3)}")

t_trn: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [95]:
print(torch.cat((t, t.t()), dim = 0).reshape(3,6))

tensor([[0, 1, 2, 3, 4, 5],
        [6, 7, 8, 0, 1, 2],
        [3, 4, 5, 6, 7, 8]])


In [98]:
x = torch.arange(3)
y = torch.rand(3)
print(f"x = {x}, \ny = {y}, \nz = {torch.cat((x, y), dim = 0).reshape(3,2)}")

x = tensor([0, 1, 2]), 
y = tensor([0.2052, 0.4762, 0.9486]), 
z = tensor([[0.0000, 1.0000],
        [2.0000, 0.2052],
        [0.4762, 0.9486]])


In [99]:
#flattening/Unrolling a tensor to 1d

In [100]:
data = torch.rand(3,5)
data_flat = data.view(-1)
print(f"data_shape: {data.shape}\ndata_flat_shape: {data_flat.shape}")

data_shape: torch.Size([3, 5])
data_flat_shape: torch.Size([15])


In [102]:
#Unrolling images in batches:
batch, height, width, channels = 64, 128,128,3
rand_img = torch.rand(batch, height,width,channels)
print(f"img_shape: {rand_img.shape}\nimg_unrolled_shape: {rand_img.view(batch, -1).shape}")

img_shape: torch.Size([64, 128, 128, 3])
img_unrolled_shape: torch.Size([64, 49152])
