<a href="https://colab.research.google.com/github/martinpius/PYTORCH/blob/main/Pytorch_the_basic_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Introduction to pytorch: How to define various types of tensors and their operations in pytorch

In [3]:
import torch
print(torch.__version__)

1.8.1+cu101


In [4]:
if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")



In [3]:
#Defining tensors in pytorch:
my_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,2]], dtype = torch.float32, device = device)

In [4]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 2.]], device='cuda:0')


In [5]:
x = torch.empty(size = (3,3), dtype = torch.float32)#Normally is supposed to be an empty space but initially it will be covered by pseudos numbers

In [6]:
print(x)

tensor([[-4.6374e+27,  3.0799e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0799e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])


In [7]:
x = torch.empty(size = (3,3)).normal_(mean = 0, std = 1) #A 3,3 tensor of std normal numbers

In [8]:
print(x)

tensor([[-1.5317, -1.0787, -0.7060],
        [ 0.3981, -0.0956,  0.8352],
        [-1.0659, -2.2093,  1.0100]])


In [9]:
x = torch.linspace(start = 0, end = 1, steps = 10)

In [10]:
print(x) #Must be numbers 0.0, 0.1 ---1.0

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [11]:
x = torch.zeros(size = (3,3), dtype = torch.float32, requires_grad=True)

In [12]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)


In [13]:
x = torch.eye(3,3, dtype = torch.float32, requires_grad = True)

In [14]:
print(x)#A diaganol matrix with ones (identity matrix)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], requires_grad=True)


In [15]:
x = torch.arange(start = 0, end = 20, step = 2, dtype = torch.int32)

In [16]:
print(x) #print numbers 0, 1, ..., 18

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=torch.int32)


In [18]:
x = torch.arange(10)
print(x.bool())#Return 10 random boolean values 

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])


In [20]:
print(x.dtype) #By default is int64

torch.int64


In [22]:
print(x.long().dtype)#We can also make sure it is int64 by change into a long int.

torch.int64


In [23]:
print(x.short().dtype)#Short returns int16

torch.int16


In [24]:
print(x.half().dtype)#half return float16

torch.float16


In [26]:
print(x.double().dtype) #returns float64

torch.float64


In [28]:
print(x.float().dtype) #returns  float32

torch.float32


In [29]:
#convert numpy arrays to tensor:

In [30]:
import numpy as np

In [36]:
arr1 = np.array((3,3), dtype = 'float32')
print(arr1)

[3. 3.]


In [37]:
tensor = torch.from_numpy(arr1)# defining a tensor from the numpy array

In [38]:
print(tensor)

tensor([3., 3.])


In [40]:
arr_back = tensor.numpy() #Get the tensor back to numpy array

In [41]:
print(arr_back)

[3. 3.]


In [42]:
#Tensor maths operations with pytorch:

In [46]:
x = torch.tensor([2,8,1], dtype = torch.float32, requires_grad = False)
y = torch.tensor([8,2,9], dtype = torch.float32, requires_grad = False)

In [47]:
holder = torch.empty(size = (1, 3)) #place holder with exactly dimension if needed"

In [49]:
out = torch.add(x,y, out = holder)

In [50]:
print(out)

tensor([10., 10., 10.])


In [51]:
#We can opt for the simple and direct operands such as 

In [52]:
out1 = torch.add(x, y)
print(out1)
out2 = x + y
print(out2)

tensor([10., 10., 10.])
tensor([10., 10., 10.])


In [60]:
#Substruction can also be done directly:
print(torch.subtract(x, y, out = holder)) 
print((x - y)) 


tensor([-6.,  6., -8.])
tensor([-6.,  6., -8.])


In [61]:
#Divission -elementwise(if of the same dimension):
out = torch.true_divide(x, y)
print(out)

tensor([0.2500, 4.0000, 0.1111])


In [63]:
#Matrices multiplication
out2 = torch.matmul(torch.eye(3,3), torch.empty(3,3).normal_(mean =0, std = 1))

In [64]:
out2

tensor([[-0.8662, -0.0381,  0.2703],
        [ 2.0528, -0.3990,  0.4157],
        [-0.0238, -1.4011,  0.5919]])

In [68]:
#exponents operations is same as ussual:
x = torch.tensor([2,3,4], dtype = torch.int32, requires_grad = False)
x_square = x.pow(2)
x_sq = x**2
print(x)
print(x_square)
print(x_sq)


tensor([2, 3, 4], dtype=torch.int32)
tensor([ 4,  9, 16], dtype=torch.int32)
tensor([ 4,  9, 16], dtype=torch.int32)


In [72]:
print(x_square > 0)

tensor([True, True, True])


In [73]:
#Other way of multiplying two matrices:

In [75]:
#**Random number for int is not implimented in torch yet.
A = torch.rand(size = (2,3),dtype = torch.float32)
B = torch.rand(size = (3,2), dtype = torch.float32)
C1 = torch.mm(A, B) #This results into a 2,2 matrix
C2 = B.mm(A) #This results into a 3,3 matrix (same operation though)
print(f"{A}\n{B}\n{C1}\n{C2}")

tensor([[0.1972, 0.1962, 0.3205],
        [0.4672, 0.7402, 0.6894]])
tensor([[0.4804, 0.1200],
        [0.8431, 0.0184],
        [0.0958, 0.6581]])
tensor([[0.2909, 0.2382],
        [0.9146, 0.5233]])
tensor([[0.1508, 0.1831, 0.2367],
        [0.1748, 0.1790, 0.2829],
        [0.3264, 0.5059, 0.4844]])


In [76]:
#matrix exponentiation and element-wise multiplication and the dotproduct: 
#(we can compute the power/cubic/higher polynomial for matrix) as follow

In [89]:
C1 = torch.tensor(([2,2],[2,2]), dtype = torch.float32)
C1_sq = C1.matrix_power(2) #Multiply matrix by itself 2 times
C_exp = C1.matrix_exp() 
C_elm = C_exp * C1_sq #Elementwise multiplication for the matrices
C_dot = torch.dot(torch.tensor([2,1,3]), torch.tensor([3,1,2])) #The dot product (return the totals of elementwise multiplication)


In [90]:
print(f"C1 = {C1}\nC_square = {C1_sq}, C_exp = {C_exp}\nC_elm = {C_elm}\nC_dot = {C_dot}")

C1 = tensor([[2., 2.],
        [2., 2.]])
C_square = tensor([[8., 8.],
        [8., 8.]]), C_exp = tensor([[27.7991, 26.7991],
        [26.7991, 27.7991]])
C_elm = tensor([[222.3926, 214.3926],
        [214.3926, 222.3926]])
C_dot = 13


In [91]:
#Multiplication of high dimension tensor (like images processing) using batch multiplication

In [92]:
batch, m, n, p = 64, 10, 30, 16

In [95]:
mat1 = torch.rand((batch, m, n)) #First matrix
mat2 = torch.rand((batch, n, p)) #Second matrix
print(f"mat1: {mat1.shape}\nmat2: {mat2.shape}")

mat1: torch.Size([64, 10, 30])
mat2: torch.Size([64, 30, 16])


In [96]:
#Now we can multiply the above as follows:
out = torch.bmm(mat1, mat2)
print(f"out = {out}\nout_shape:{out.shape}")

out = tensor([[[ 6.9650,  8.9363,  8.9309,  ...,  5.7759,  7.9629,  6.8339],
         [ 5.9264,  6.9877,  6.8562,  ...,  5.2875,  5.9767,  5.6455],
         [ 6.5541,  8.4146,  8.4222,  ...,  6.2149,  7.2208,  6.5551],
         ...,
         [ 9.7873, 10.9773, 10.8121,  ...,  7.6806,  9.1131,  8.0161],
         [ 7.2786,  9.6606,  8.4922,  ...,  5.9987,  6.9572,  7.1495],
         [ 8.0520,  8.8957,  8.0369,  ...,  6.4429,  7.6086,  6.0644]],

        [[ 7.2354,  7.4031,  6.3473,  ...,  7.5578,  8.4306,  7.7924],
         [ 7.9068,  6.1881,  7.4880,  ...,  7.8382,  8.6875,  8.8734],
         [ 8.6335,  6.7787,  7.2422,  ...,  7.7716,  8.3427,  8.9197],
         ...,
         [ 7.5441,  5.7748,  6.5634,  ...,  7.4472,  8.1620,  8.1454],
         [ 8.3442,  6.2337,  6.5437,  ...,  7.3355,  7.4428,  8.5428],
         [ 7.5248,  6.0900,  6.8386,  ...,  7.4969,  8.2308,  8.4342]],

        [[ 7.5589,  8.5400,  8.0699,  ...,  8.2805,  9.9820,  8.3092],
         [ 7.4627,  7.5285,  7.5216,  .

In [97]:
#Broadcasting in pytorch is same as in numpy or tensorflow:

In [98]:
x = torch.rand(3,4)

In [99]:
y = torch.rand(1,4)

In [100]:
print(f"x_shape: {x.shape}, y_shape: {y.shape}")

x_shape: torch.Size([3, 4]), y_shape: torch.Size([1, 4])


In [101]:
print(f"x = {x}\ny = {y}")

x = tensor([[0.0645, 0.4598, 0.5354, 0.9435],
        [0.3989, 0.4853, 0.2050, 0.4193],
        [0.5009, 0.2589, 0.8305, 0.9537]])
y = tensor([[0.6245, 0.7844, 0.9467, 0.3469]])


In [102]:
#We can perform operations as ussual and broadcasting will be applied to the smaller tensor to match the dimension of the bigger

In [103]:
print(f"{x - y}\n{x+y}\n{x**y}")

tensor([[-0.5599, -0.3246, -0.4113,  0.5966],
        [-0.2256, -0.2991, -0.7416,  0.0724],
        [-0.1235, -0.5255, -0.1162,  0.6068]])
tensor([[0.6890, 1.2441, 1.4821, 1.2904],
        [1.0233, 1.2697, 1.1517, 0.7662],
        [1.1254, 1.0432, 1.7772, 1.3007]])
tensor([[0.1806, 0.5436, 0.5535, 0.9800],
        [0.5633, 0.5672, 0.2231, 0.7397],
        [0.6494, 0.3464, 0.8387, 0.9837]])


In [106]:
print(f"max_val: {torch.max(x, dim = 1)}\nmin_val: {torch.min(y, dim = 1)}")

max_val: torch.return_types.max(
values=tensor([0.9435, 0.4853, 0.9537]),
indices=tensor([3, 1, 3]))
min_val: torch.return_types.min(
values=tensor([0.3469]),
indices=tensor([3]))


In [110]:
print(f"arg_max: {torch.argmax(x, dim = 1)}\narg_min: {torch.argmin(y, dim = 1)}\nabsolute_x:{torch.abs(x)}\nequality: {torch.eq((x - y), (x + y))}")

arg_max: tensor([3, 1, 3])
arg_min: tensor([3])
absolute_x:tensor([[0.0645, 0.4598, 0.5354, 0.9435],
        [0.3989, 0.4853, 0.2050, 0.4193],
        [0.5009, 0.2589, 0.8305, 0.9537]])
equality: tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [113]:
z = torch.clamp(x-y, min = 0, max = 3)

In [114]:
print(z)

tensor([[0.0000, 0.0000, 0.0000, 0.5966],
        [0.0000, 0.0000, 0.0000, 0.0724],
        [0.0000, 0.0000, 0.0000, 0.6068]])


In [115]:
print(torch.mean(z.float(), dim = 1)) #compute the mean for specified dimension

tensor([0.1491, 0.0181, 0.1517])


In [5]:
#Tensor_indexing:
batch_size, features = 32, 10

In [7]:
data = torch.rand(batch_size, features)

In [8]:
#Grabbing the features of the first sample:
display(data[0])

tensor([0.5048, 0.6400, 0.6801, 0.4147, 0.0488, 0.5096, 0.5033, 0.5764, 0.8844,
        0.6777])

In [9]:
#Display the features of the last sample:

In [10]:
display(data[-1])

tensor([0.0530, 0.0338, 0.4162, 0.5764, 0.7073, 0.1908, 0.1277, 0.2591, 0.2269,
        0.3842])

In [11]:
#Display the features of some samples:
for ft in data[0:5]:
  print(ft)

tensor([0.5048, 0.6400, 0.6801, 0.4147, 0.0488, 0.5096, 0.5033, 0.5764, 0.8844,
        0.6777])
tensor([0.4369, 0.3155, 0.4764, 0.2740, 0.5329, 0.3384, 0.3764, 0.5561, 0.5326,
        0.4818])
tensor([0.3285, 0.2639, 0.8477, 0.2231, 0.1917, 0.7057, 0.4472, 0.7450, 0.6869,
        0.2176])
tensor([0.6338, 0.2170, 0.4985, 0.5126, 0.9581, 0.3935, 0.1880, 0.7402, 0.6654,
        0.4142])
tensor([0.6274, 0.5999, 0.1230, 0.6296, 0.9639, 0.7494, 0.7001, 0.7913, 0.6018,
        0.2761])


In [12]:
#Get the first feature for all samples:

In [13]:
display(data[:,0])

tensor([0.5048, 0.4369, 0.3285, 0.6338, 0.6274, 0.4844, 0.8384, 0.4464, 0.8842,
        0.6353, 0.6814, 0.3382, 0.6137, 0.9762, 0.2814, 0.5197, 0.7950, 0.0248,
        0.8560, 0.5530, 0.4453, 0.6744, 0.3739, 0.5210, 0.6370, 0.7962, 0.1519,
        0.4150, 0.6933, 0.6553, 0.1606, 0.0530])

In [15]:
#Other way to get all features for an example (say 1):
display(data[0:,1])

tensor([0.6400, 0.3155, 0.2639, 0.2170, 0.5999, 0.9555, 0.4438, 0.9978, 0.4987,
        0.9720, 0.2303, 0.4020, 0.0123, 0.3130, 0.7152, 0.9997, 0.5303, 0.1336,
        0.0579, 0.7031, 0.1851, 0.3694, 0.4478, 0.6449, 0.6613, 0.7230, 0.8571,
        0.9120, 0.4625, 0.5357, 0.8054, 0.0338])

In [16]:
#All features and all examples:

In [20]:
display(data.shape)

torch.Size([32, 10])

In [19]:
#Same as
display(data[0:,].shape)

torch.Size([32, 10])

In [21]:
#Get some features of a specified sample:

In [23]:
display(data[0,0:5]) #display the first five features of the first sample data

tensor([0.5048, 0.6400, 0.6801, 0.4147, 0.0488])

In [24]:
#Get all first 5 features of all examples:

In [25]:
display(data[0:, 0:5].shape)

torch.Size([32, 5])